Add TypeScript typings
tschaub/es-main pull request #10
Opened 2020-12-10 13:03 UTC by sidvishnoi

Closes https://github.com/tschaub/es-main/issues/9

2021-06-08 07:47 UTC, remcohaszing approved these changes
LGTM

2021-07-17 22:14 UTC, micalevisk approved these changes
LGTM as well

2021-07-17 22:18 UTC, micalevisk requested changes
actually could you please add the type defs for this new function?

https://github.com/tschaub/es-main/blob/8a569c0ca2345221e62a1dedeb00f9a29301178f/main.js#L5-L12

2021-12-31 19:59 UTC, cinderblock commented
```ts
export default function (meta: ImportMeta): boolean;
export function stripExt(name: String): String;
```

2021-12-31 21:18 UTC, micalevisk requested changes
please add this

2021-12-31 21:19 UTC, micalevisk commented on main.d.ts
> +export default function (meta: ImportMeta): boolean;
```suggestion
export default function (meta: ImportMeta): boolean;
export function stripExt(name: string): string;
```

2022-04-05 18:40 UTC, q-garethallenstringer approved these changes

2022-05-11 21:12 UTC, cinderblock commented
We could also add JSDoc comments to the published `main.d.ts` to annotate the function with a little more detail in code editors.

2022-06-28 13:32 UTC, hasparus commented
Hey @tschaub, I'd hate to annoy you, but is there a chance of merging this in the future?
Do you need some help getting it past the finish line, or would you prefer the typings to live in DefinitelyTyped?

2022-06-28 16:23 UTC, tschaub commented
Thanks for the proposed contribution @sidvishnoi and to the others here for the reviews and suggestions.

In #24, JSDoc comments were added with the types and documentation for the exported functions.  The `main.d.ts` and `main.d.ts.map` files are generated from these comments.  The 1.1.1 release includes these, so I hope things should work better for TypeScript users now.

2022-06-28 16:23 UTC, closed without merging